// Vue/src/components/Navbar.vue
<template>
  <nav class="navbar">
    <router-link to="/" class="navbar-logo">
      <img src="@/assets/logo.svg" alt="Home" class="logo" />
    </router-link>

    <!-- Profile Icon -->
    <div class="navbar-profile">
      <router-link to="/profile">
        <img src="@/assets/user-regular.svg" alt="Profile" class="profile-icon" />
      </router-link>
    </div>
  </nav>
</template>

<script>
export default {
  name: 'Navbar'
};
</script>

<style scoped>
.navbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 20px;
  background-color: white;
  width: 90vw;
}
.navbar-logo .logo {
  height: 50px;
}

.navbar-profile .profile-icon {
  height: 40px;
  cursor: pointer;
}
</style>

// React/src/components/navbar.jsx
import { Link } from 'react-router-dom';
import reactLogo from '../assets/react.svg'
import profile from '../assets/user-regular.svg'
import '../css/navbar.css'

export default function Navbar() {
  return (
    <nav className="navbar">
      <Link to="/" className="navbar-logo">
        <img src={reactLogo} alt="Home" className="logo" />
      </Link>

      {/* Profile Icon */}
      <div className="navbar-profile">
        <Link to="/profile">
          <img src={profile} alt="Profile" className="profile-icon" />
        </Link>
      </div>
    </nav>
  );
}
